apiVersion: apps/v1
kind: Deployment
metadata:
  name: rojeckeg098
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rojeckeg098
  template:
    metadata:
      labels:
        app: rojeckeg098
    spec:
      containers:
      - image: okteto.dev/rojeckeg098:latest
        name: rojeckeg098
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "20894fc5-7cb9-48bb-b0ce-1e5a073a091c"
        - name: Vless_Path
          value: "/ielskdjf2345"
        - name: Vmess_UUID
          value: "1674b3f8-8506-40f5-b530-79fa8ef2c985"
        - name: Vmess_Path
          value: "/yeodkfaw7890"
        - name: Share_Path
          value: "/v2link"
